#!/usr/bin/env python3
path = '/home/pro/DKN/dadeh-kesht-novin/apps/web/src/app/(app)/dashboard/page.tsx'
with open(path, 'w', encoding='utf-8') as f:
    f.write("'use client';\n")
    f.write("import { useState, useEffect } from 'react';\n")
    f.write("import { useRouter } from 'next/navigation';\n\n")
    f.write("export default function DashboardPage() {\n")
    f.write("  const router = useRouter();\n")
    f.write("  const [user, setUser] = useState(null);\n")
    f.write("  const [farms, setFarms] = useState([]);\n")
    f.write("  const [weather, setWeather] = useState(null);\n")
    f.write("  const [loading, setLoading] = useState(true);\n\n")
    f.write("  useEffect(() => {\n")
    f.write("    const token = localStorage.getItem('token');\n")
    f.write("    if (!token) { router.push('/'); return; }\n")
    f.write("    Promise.all([\n")
    f.write("      fetch('/api/v1/auth/profile', { headers: { Authorization: 'Bearer ' + token } }).then(r => r.json()),\n")
    f.write("      fetch('/api/v1/farms', { headers: { Authorization: 'Bearer ' + token } }).then(r => r.json()),\n")
    f.write("    ]).then(async ([u, f]) => {\n")
    f.write("      if (u.firstName) { setUser(u); localStorage.setItem('user', JSON.stringify(u)); }\n")
    f.write("      const fl = Array.isArray(f) ? f : [];\n")
    f.write("      setFarms(fl);\n")
    f.write("      if (fl.length > 0) {\n")
    f.write("        try {\n")
    f.write("          const res = await fetch('/api/v1/weather/' + fl[0].id + '/dashboard?city=' + encodeURIComponent(fl[0].city || 'Saveh'), {\n")
    f.write("            headers: { Authorization: 'Bearer ' + token }\n")
    f.write("          });\n")
    f.write("          if (res.ok) setWeather(await res.json());\n")
    f.write("        } catch {}\n")
    f.write("      }\n")
    f.write("      setLoading(false);\n")
    f.write("    }).catch(() => setLoading(false));\n")
    f.write("  }, [router]);\n\n")
    f.write("  if (loading) return <div className='flex items-center justify-center h-40'><p className='text-gray-400 text-sm'>loading</p></div>;\n")
    f.write("  if (farms.length === 0) return <div className='text-center mt-12'><h1>No farms yet</h1><button onClick={() => router.push('/setup')}>Create farm</button></div>;\n")
    f.write("  const farm = farms[0];\n")
    f.write("  const loc = [farm.city, farm.province].filter(Boolean).join(' - ') || 'N/A';\n")
    f.write("  const w = weather?.current;\n")
    f.write("  const forecast = weather?.forecast || [];\n")
    f.write("  const daysSince = weather?.lastIrrigation ? Math.floor((Date.now() - new Date(weather.lastIrrigation.date).getTime()) / 86400000) : null;\n")
    f.write("  return <><div>{farm.name}</div>{w && <div>Temp: {w.temperature}C Humidity: {w.humidity}%</div>}</>;\n")
    f.write("}\n")
print('Created dashboard page.tsx')
